### ISSUE TITLE
No matching distribution found for autoawq==0.2.3

### ISSUE THREAD

**Issue by DDecoene** [thisserand/llama3_local#1]
This is my hardware:

  Model Name:	MacBook Air
  Model Identifier:	Mac14,2
  Model Number:	MLY33FN/A
  Chip:	Apple M2
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	8 GB

**Comment by baditaflorin** [comment]
Commenting the autoawq package leds to another error
pip3 install -r requirements.txt
```
Collecting flash-attn==2.5.7 (from -r requirements.txt (line 2))
  Downloading flash_attn-2.5.7.tar.gz (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 1.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/florin/Documents/GITHUB_PROJECTS/llama3_local/llama3_venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/florin/Documents/GITHUB_PROJECTS/llama3_local/llama3_venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/florin/Documents/GITHUB_PROJECTS/llama3_local/llama3_venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/_w/m38196x96cs9ptvv1j0srlp80000gp/T/pip-build-env-68sll0j1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/_w/m38196x96cs9ptvv1j0srlp80000gp/T/pip-build-env-68sll0j1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/_w/m38196x96cs9ptvv1j0srlp80000gp/T/pip-build-env-68sll0j1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/_w/m38196x96cs9ptvv1j0srlp80000gp/T/pip-build-env-68sll0j1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 9, in <module>
      ModuleNotFoundError: No module named 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by thisserand** [comment]
Can you maybe check your pip config? On PyPi you can see that 2.5.7 is the second most recent version for flash-attn: https://pypi.org/project/flash-attn/#history

**Comment by KateParshina** [comment]
@baditaflorin you can find the answer here - https://github.com/casper-hansen/AutoAWQ/issues/163
The autoawq is not available for Mac.

**Comment by brlocky** [comment]
I'm also getting this in Windows 10

```
pip install -r requirements.txt

ERROR: Could not find a version that satisfies the requirement autoawq==0.2.3 (from versions: none)
ERROR: No matching distribution found for autoawq==0.2.3
```

**Comment by rahulthetoolsmaker** [comment]
I am also getting this in windows 11

`pip install -r requirements.txt
Collecting autoawq==0.2.3 (from -r requirements.txt (line 1))
  Downloading autoawq-0.2.3-cp311-cp311-win_amd64.whl.metadata (16 kB)
Collecting flash-attn==2.5.7 (from -r requirements.txt (line 2))
  Downloading flash_attn-2.5.7.tar.gz (2.5 MB)
     ---------------------------------------- 2.5/2.5 MB 31.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1`
